### PR TITLE
Added Visualization for BFS Algorithm

### LINKED ISSUE #18: add visualization for Dfs and Bfs

### PR DESCRIPTION
**Pull request by RishavMz**
fixes #18

Description: Added BreadthFirstSearch Traversal Visualization

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial

Screenshot (48)

### CODE REVIEW

**Review by tusharjain0022 — APPROVED** [review]
LGTM! ⭐

**Review by EmperorYP7 — CHANGES_REQUESTED** [review]
There are several cases where the animation or rather the whole website is completely frozen. If the walls are placed in such a way that there is no possible way, the program just continues to run indefinitely for some reason. Would you like to investigate about it @ankiiitraj?

**Comment by RishavMz** [comment]
Thanks for mentioning it @EmperorYP7,  I just found that the application was entering into an infinite loop in case of no possible paths, leading to freezing of the browser.

I have fixed this bug in my later commits

**Review by EmperorYP7 — APPROVED** [review]

**Comment by anktrj** [comment]
There are certain things that can be made better 
 - Like creating obstacles.
 - And adding more frames to the animation
 Ping me if you've any problems!

**Comment by EmperorYP7** [comment]
Heads up @RishavMz!

**Comment by RishavMz** [comment]
Yes, an option to auto generate obstacles ( as a maze or randomly ) would be great. I'm on it...

But @ankiiitraj can increasing frames be done by slowing down the animation delay , or by adding more set images in queue to be displayed on screen???

**Comment by anktrj** [comment]
You got it right talking about adding more set of states/images to the queue!

**Comment by anktrj** [comment]
As of now merging this, and creating an issue for more refined animation! What do you say @RishavMz

**Comment by RishavMz** [comment]
Sure @ankiiitraj Sir. 
I would try to implement those changes in a while suggested by you in a later PR referring to that issue .

**Comment by EmperorYP7** [comment]
Alright then, merging this.

**Pull request merged**
